package com.wms.inbound.application.service;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import com.wms.inbound.application.command.ReceiveAsnCommand;
import com.wms.inbound.application.port.out.AsnNoSequencePort;
import com.wms.inbound.application.port.out.AsnPersistencePort;
import com.wms.inbound.application.port.out.InboundEventPort;
import com.wms.inbound.application.port.out.MasterReadModelPort;
import com.wms.inbound.application.result.AsnResult;
import com.wms.inbound.domain.event.AsnReceivedEvent;
import com.wms.inbound.domain.exception.AsnNoDuplicateException;
import com.wms.inbound.domain.exception.PartnerInvalidTypeException;
import com.wms.inbound.domain.exception.WarehouseNotFoundInReadModelException;
import com.wms.inbound.domain.model.masterref.PartnerSnapshot;
import com.wms.inbound.domain.model.masterref.SkuSnapshot;
import com.wms.inbound.domain.model.masterref.WarehouseSnapshot;
import java.time.Clock;
import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneOffset;
import java.util.List;
import java.util.Optional;
import java.util.Set;
import java.util.UUID;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.security.access.AccessDeniedException;

@ExtendWith(MockitoExtension.class)
class ReceiveAsnServiceTest {

    private static final Instant FIXED_NOW = Instant.parse("2026-04-29T10:00:00Z");

    @Mock AsnPersistencePort asnPersistence;
    @Mock AsnNoSequencePort asnNoSequence;
    @Mock InboundEventPort eventPort;
    @Mock MasterReadModelPort masterReadModel;

    ReceiveAsnService sut;

    UUID warehouseId;
    UUID partnerId;
    UUID skuId;
    WarehouseSnapshot activeWarehouse;
    PartnerSnapshot activeSupplier;
    SkuSnapshot activeSku;

    @BeforeEach
    void setUp() {
        sut = new ReceiveAsnService(asnPersistence, asnNoSequence, eventPort, masterReadModel,
                Clock.fixed(FIXED_NOW, ZoneOffset.UTC));

        warehouseId = UUID.randomUUID();
        partnerId = UUID.randomUUID();
        skuId = UUID.randomUUID();

        activeWarehouse = new WarehouseSnapshot(warehouseId, "WH01",
                WarehouseSnapshot.Status.ACTIVE, FIXED_NOW, 1L);
        activeSupplier = new PartnerSnapshot(partnerId, "SUP-001",
                PartnerSnapshot.PartnerType.SUPPLIER, PartnerSnapshot.Status.ACTIVE, FIXED_NOW, 1L);
        activeSku = new SkuSnapshot(skuId, "SKU-001",
                SkuSnapshot.TrackingType.NONE, SkuSnapshot.Status.ACTIVE, FIXED_NOW, 1L);
    }

    @Test
    void receive_happyPath_savesAsnAndPublishesEvent() {
        when(masterReadModel.findWarehouse(warehouseId)).thenReturn(Optional.of(activeWarehouse));
        when(masterReadModel.findPartner(partnerId)).thenReturn(Optional.of(activeSupplier));
        when(masterReadModel.findSku(skuId)).thenReturn(Optional.of(activeSku));
        when(asnPersistence.existsByAsnNo("ASN-001")).thenReturn(false);
        when(asnPersistence.save(any())).thenAnswer(inv -> inv.getArgument(0));

        AsnResult result = sut.receive(command("ASN-001", "user-1", Set.of("ROLE_INBOUND_WRITE")));

        assertThat(result.asnNo()).isEqualTo("ASN-001");
        assertThat(result.status()).isEqualTo("CREATED");
        assertThat(result.warehouseId()).isEqualTo(warehouseId);
        verify(asnPersistence).save(any());
        verify(eventPort).publish(any(AsnReceivedEvent.class));
    }

    @Test
    void receive_nullAsnNo_usesAutoGeneratedSequence() {
        when(masterReadModel.findWarehouse(warehouseId)).thenReturn(Optional.of(activeWarehouse));
        when(masterReadModel.findPartner(partnerId)).thenReturn(Optional.of(activeSupplier));
        when(masterReadModel.findSku(skuId)).thenReturn(Optional.of(activeSku));
        when(asnNoSequence.nextAsnNo()).thenReturn("ASN-20260429-0001");
        when(asnPersistence.existsByAsnNo("ASN-20260429-0001")).thenReturn(false);
        when(asnPersistence.save(any())).thenAnswer(inv -> inv.getArgument(0));

        ReceiveAsnCommand cmd = new ReceiveAsnCommand(
                null, "MANUAL", partnerId, warehouseId,
                LocalDate.of(2026, 5, 1), null,
                List.of(new ReceiveAsnCommand.Line(skuId, null, 10)),
                "user-1", Set.of("ROLE_INBOUND_WRITE"));

        AsnResult result = sut.receive(cmd);

        assertThat(result.asnNo()).isEqualTo("ASN-20260429-0001");
        verify(asnNoSequence).nextAsnNo();
    }

    @Test
    void receive_duplicateAsnNo_throwsAsnNoDuplicateException() {
        when(masterReadModel.findWarehouse(warehouseId)).thenReturn(Optional.of(activeWarehouse));
        when(masterReadModel.findPartner(partnerId)).thenReturn(Optional.of(activeSupplier));
        when(asnPersistence.existsByAsnNo("DUP-001")).thenReturn(true);

        assertThatThrownBy(() -> sut.receive(command("DUP-001", "user-1", Set.of("ROLE_INBOUND_WRITE"))))
                .isInstanceOf(AsnNoDuplicateException.class);

        verify(asnPersistence, never()).save(any());
        verify(eventPort, never()).publish(any());
    }

    @Test
    void receive_warehouseNotFoundInReadModel_throwsWarehouseNotFound() {
        when(masterReadModel.findWarehouse(warehouseId)).thenReturn(Optional.empty());

        assertThatThrownBy(() -> sut.receive(command("ASN-X", "user-1", Set.of("ROLE_INBOUND_WRITE"))))
                .isInstanceOf(WarehouseNotFoundInReadModelException.class);
    }

    @Test
    void receive_partnerCannotSupply_throwsPartnerInvalidType() {
        PartnerSnapshot carrier = new PartnerSnapshot(partnerId, "CAR-001",
                PartnerSnapshot.PartnerType.CARRIER, PartnerSnapshot.Status.ACTIVE, FIXED_NOW, 1L);
        when(masterReadModel.findWarehouse(warehouseId)).thenReturn(Optional.of(activeWarehouse));
        when(masterReadModel.findPartner(partnerId)).thenReturn(Optional.of(carrier));

        assertThatThrownBy(() -> sut.receive(command("ASN-X", "user-1", Set.of("ROLE_INBOUND_WRITE"))))
                .isInstanceOf(PartnerInvalidTypeException.class);
    }

    @Test
    void receive_missingRole_throwsAccessDenied() {
        assertThatThrownBy(() -> sut.receive(command("ASN-X", "user-no-role", Set.of())))
                .isInstanceOf(AccessDeniedException.class);

        verify(masterReadModel, never()).findWarehouse(any());
    }

    @Test
    void receive_systemActor_skipsRoleCheck() {
        when(masterReadModel.findWarehouse(warehouseId)).thenReturn(Optional.of(activeWarehouse));
        when(masterReadModel.findPartner(partnerId)).thenReturn(Optional.of(activeSupplier));
        when(masterReadModel.findSku(skuId)).thenReturn(Optional.of(activeSku));
        when(asnPersistence.existsByAsnNo(anyString())).thenReturn(false);
        when(asnPersistence.save(any())).thenAnswer(inv -> inv.getArgument(0));

        ReceiveAsnCommand cmd = new ReceiveAsnCommand(
                "ASN-SYS-001", "WEBHOOK_ERP", partnerId, warehouseId,
                LocalDate.of(2026, 5, 1), null,
                List.of(new ReceiveAsnCommand.Line(skuId, null, 5)),
                "system:erp-webhook", Set.of());

        AsnResult result = sut.receive(cmd);

        assertThat(result.asnNo()).isEqualTo("ASN-SYS-001");
        verify(eventPort).publish(any(AsnReceivedEvent.class));
    }

    // -------------------------------------------------------------------------
    // helpers
    // -------------------------------------------------------------------------

    private ReceiveAsnCommand command(String asnNo, String actorId, Set<String> roles) {
        return new ReceiveAsnCommand(
                asnNo, "MANUAL", partnerId, warehouseId,
                LocalDate.of(2026, 5, 1), "test notes",
                List.of(new ReceiveAsnCommand.Line(skuId, null, 10)),
                actorId, roles);
    }
}
